# Base image
FROM python:3.11-slim-trixie

WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.10.12 /uv /uvx /bin/

# Install dependencies
COPY pyproject.toml uv.lock ./
RUN uv sync --locked

# Copy project code
COPY . .

ENTRYPOINT ["uv", "run", "python", "src/train.py"]
CMD ["--help"]
